module.exports = {
	LOCALE_RUNNING: 'LOCALE is running on PORT',
	SUCCESS: 'success',

	TRANSACTION_RESPONSE: 'Balance Retrieved',
	TRANSACTION_LIST_RESPONSE: 'Transaction History Retrieved',
	FAIL: 'fail',
	v1: '/api/v1',
	EMAIL_CONFLICT: 'A user with your email already exists',
	THIRD_PARTY_ERROR: 'Error From Third Party Api',
	WELCOME:
		'Welcome to Locale Api, Everything you need about Nigeria GEO',
	INVALID_CREDENTIALS: 'Incorrect login details',
	INVALID_PERMISSION:
		'Permission denied. Invalid credentials provided',
	INVALID_ACCOUNT_NO: 'Invalid account NO',
	NO_BENEFICIARY_FOUND: 'No benefic found please create one',
	INSUFICIENT_FUNDS: "You don't have sufficient funds",
	USER_SIGNUP_SUCCESS: 'Account created successfully',
	MODULE_ERROR_STATUS: 'MODULE_PROCESS_BROKE',
	MODULE_ERROR: 'A module error occurred',
	DB_SUCCESS: 'Database connected',
	DB_ERROR_STATUS: 'DB_PROCESS_FAILED',
	DB_ERROR: 'A database error occurred',
	FORBIDDEN: 'Access forbidden. You do not have the required access.',
	CREATE_USER_ERROR: 'Error creating user',
	CREATE_USER_SUCCESS: 'Created user successfully',
	CHAINAMB_CHAIN_ERROR: 'Campaign already chained by You',
	CHAIN_SUCCESS: 'You have successfully chained this campaign',
	USER_CHAIN_ERROR: 'Cannot chain campaign created by you',
	USER_ALREADY_EXIST: 'USER exists already',
	USERNAME_ALREADY_EXIST: 'USERNAME exists already',
	USER_EXIST_VERIFICATION_FAIL: 'USER_EMAIL_EXIST_VERIFICATION_FAIL',
	USER_EMAIL_EXIST_VERIFICATION_FAIL:
		'USER_EMAIL_EXIST_VERIFICATION_FAIL',
	USER_EMAIL_EXIST_VERIFICATION_FAIL_MSG:
		'Login failed. It is not you, it is us.',
	INTERNAL_SERVER_ERROR: 'Oops, something broke on the server!!!',
	LOGIN_USER_SUCCESSFULLY: 'Login Successful',
	INVALID_EMAIL:
		'This email does not exist, please enter a registered email',
	USER_NOT_FOUND: 'User not found',
	ERROR_FETCHING_USER: 'Error fetching user',
	ERROR_VERIFYING_USER: 'ERROR VERIFYING USER',
	ERROR_VERIFYING_USER_MSG:
		'Error trying to verify user. It is not you, it is us.',
	NOT_FOUND_API: 'Oops, You have reached a dead end',
	ACCESS_REVOKED: 'ACCESS REVOKED',
	AUTH_REQUIRED: 'Access denied,a valid access token is required',
};
